### ISSUE TITLE
extended password manager with (acm) access control management with categories of credentials

### ISSUE THREAD

**Issue by ghost** [jaydip-pawar/Secret-Keeper#1]
Hi @jaydip-pawar ,

Hope you are all well !

I am just dropping this message as I would like to create a teampass (https://teampass.net/) clone with flutter.

What would you advice me to use as an architecture for managing permission rights to items categories with view/edit/delete capability per categories or items. I found [flutter_rbac](https://github.com/wilpar/flutter_rbac) or [dart-casbin](https://github.com/casbin/dart-casbin) and [animated_tree_view](https://github.com/embraceitmobile/animated_tree_view)

Screenshot of teampass:
![pf_tp_5](https://user-images.githubusercontent.com/1963546/143861629-3a6c67c6-c11b-492b-a96a-5714bddbc5bb.png)

The bottleneck I see, is that have I have 30k items to hook in the the tree view. Is It possible to make the tree view searchable ?

Thanks for any insights or inputs to help me to bootstrap this project.

Cheers,
Luc

**Comment by jaydip-pawar** [comment]
Hey @lucmichalski,

I understand your question and in my opinion don't use any external library for permission control, It'll take some additional time but you can control all things in future, apart from this I think go with **dart-casbin** as it's providing many features and If you're using firebase in your project then you can go with **flutter_rbac** as it'll be familiar with your code, and If you think you can make it from scratch then you can refer [this.](https://stackoverflow.com/questions/60616919/role-based-authorization-and-role-based-access-control-flutter) 

I haven't researched on this topic much, but If you find anything you can freely contact at my email.

Good wishes with your project :-)
